export const mockLocations = [
  { id: "loc1", name: "Venice", area: "Venice", lat: 33.9850, lng: -118.4695 },
  { id: "loc2", name: "Culver City", area: "Culver City", lat: 34.0211, lng: -118.3965 },
  { id: "loc3", name: "West Hollywood", area: "West Hollywood", lat: 34.0900, lng: -118.3617 },
  { id: "loc4", name: "Silver Lake", area: "Silver Lake", lat: 34.0869, lng: -118.2698 },
  { id: "loc5", name: "Koreatown", area: "Koreatown", lat: 34.0587, lng: -118.3006 },
  { id: "loc6", name: "Inglewood", area: "Inglewood", lat: 33.9617, lng: -118.3531 },
  { id: "loc7", name: "Echo Park", area: "Echo Park", lat: 34.0782, lng: -118.2606 },
  { id: "loc8", name: "Palms", area: "Palms", lat: 34.0094, lng: -118.4068 },
  { id: "loc9", name: "Los Feliz", area: "Los Feliz", lat: 34.1050, lng: -118.2864 },
  { id: "loc10", name: "Leimert Park", area: "Leimert Park", lat: 33.9839, lng: -118.3341 },
];

export const mockSpots = [
  { id: "venice", name: "Venice Beach Pickup", area: "Venice", address: "123 Ocean Front Walk, Venice, CA" },
  { id: "overland", name: "Overland Ave Pickup", area: "Overland", address: "456 Overland Ave, Los Angeles, CA" },
  { id: "downtown", name: "Downtown LA Pickup", area: "Downtown", address: "789 S Main St, Los Angeles, CA" }
];

// ✅ MORE RESTAURANTS!
export const mockRestaurants = [
  { id: "rest1", name: "Taco Haven", pickupSpotId: "aids-project-los-angeles-vance-north-necessities-o", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest2", name: "Pizza Slice", pickupSpotId: "aaron-community-cultural-center", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest3", name: "Curry House", pickupSpotId: "aaron-community-cultural-center", description: "Warm Indian curries", hours: "11am-4pm" },
  { id: "rest4", name: "Sandwich Spot", pickupSpotId: "action-food-pantry", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest5", name: "Breakfast Club", pickupSpotId: "aids-food-store-the", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest6", name: "Juice Bar", pickupSpotId: "aids-food-store-the", description: "Fresh pressed juices", hours: "9am-1pm" },
  { id: "rest7", name: "Burger Barn", pickupSpotId: "aids-project-los-angeles-vance-north-necessities-o-2", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest8", name: "BBQ Stop", pickupSpotId: "aids-project-los-angeles-vance-north-necessities-o-3", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest9", name: "Rice Bowl Co", pickupSpotId: "aids-project-los-angeles-vance-north-necessities-o-3", description: "Asian-style rice bowls", hours: "10am-2pm" },
  { id: "rest10", name: "The Deli", pickupSpotId: "aids-project-los-angeles-vance-north-necessities-o-4", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest11", name: "Salad Works", pickupSpotId: "all-peoples-christian-center", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest12", name: "Waffle House", pickupSpotId: "all-peoples-christian-center", description: "Sweet and savory waffles", hours: "8am-1pm" },
  { id: "rest13", name: "Mediterranean Spot", pickupSpotId: "altadena-seventhday-adventist-church", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest14", name: "Taqueria Local", pickupSpotId: "amigos-sin-barreras-friends-without-barriers-circl", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest15", name: "Bento Box", pickupSpotId: "amigos-sin-barreras-friends-without-barriers-circl", description: "Japanese bento meals", hours: "12pm-5pm" },
  { id: "rest16", name: "The Grain Bowl", pickupSpotId: "angelica-lutheran-church", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest17", name: "Empanada Stand", pickupSpotId: "antelope-valley-partners-for-health", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest18", name: "Noodle Bar", pickupSpotId: "antelope-valley-partners-for-health", description: "Stir-fried noodle dishes", hours: "12pm-4pm" },
  { id: "rest19", name: "Crepe Cart", pickupSpotId: "audubon-middle-school", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest20", name: "The Bakery", pickupSpotId: "banning-senior-high-school", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest21", name: "Falafel King", pickupSpotId: "banning-senior-high-school", description: "Crispy falafel wraps", hours: "10am-4pm" },
  { id: "rest22", name: "Dumpling House", pickupSpotId: "barack-obama-preparation-academy", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest23", name: "Taco Haven", pickupSpotId: "beauty-of-holiness-church", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest24", name: "Veggie Bowl", pickupSpotId: "beauty-of-holiness-church", description: "Healthy vegan bowls", hours: "10am-2pm" },
  { id: "rest25", name: "Pizza Slice", pickupSpotId: "bell-senior-high-school", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest26", name: "Sandwich Spot", pickupSpotId: "belvedere-middle-school", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest27", name: "Soup Kitchen", pickupSpotId: "belvedere-middle-school", description: "Hot soup and bread", hours: "11am-5pm" },
  { id: "rest28", name: "Breakfast Club", pickupSpotId: "berendo-middle-school", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest29", name: "Burger Barn", pickupSpotId: "bernstein-senior-high-school", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest30", name: "Pasta Place", pickupSpotId: "bernstein-senior-high-school", description: "Homemade pasta dishes", hours: "11am-3pm" },
  { id: "rest31", name: "BBQ Stop", pickupSpotId: "bethel-food-bank-outreach", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest32", name: "The Deli", pickupSpotId: "bienestar-human-services", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest33", name: "Pho Corner", pickupSpotId: "bienestar-human-services", description: "Vietnamese noodle soup", hours: "11am-4pm" },
  { id: "rest34", name: "Salad Works", pickupSpotId: "boys-girls-club-of-metro-los-angeles-challengers-c", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest35", name: "Mediterranean Spot", pickupSpotId: "boys-girls-club-of-metro-los-angeles-jordan-downs", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest36", name: "Smoothie Stand", pickupSpotId: "boys-girls-club-of-metro-los-angeles-jordan-downs", description: "Fresh fruit smoothies", hours: "9am-2pm" },
  { id: "rest37", name: "Taqueria Local", pickupSpotId: "boys-girls-club-of-metro-los-angeles-watts-willowb", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest38", name: "The Grain Bowl", pickupSpotId: "burbank-middle-school", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest39", name: "Hot Plates", pickupSpotId: "burbank-middle-school", description: "Daily hot plate specials", hours: "11am-5pm" },
  { id: "rest40", name: "Empanada Stand", pickupSpotId: "byrd-middle-school", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest41", name: "Crepe Cart", pickupSpotId: "catholic-charities-of-los-angeles-glendale-communi", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest42", name: "Wings & Things", pickupSpotId: "catholic-charities-of-los-angeles-glendale-communi", description: "Crispy chicken wings", hours: "12pm-6pm" },
  { id: "rest43", name: "The Bakery", pickupSpotId: "catholic-charities-of-los-angeles-guadalupe-commun", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest44", name: "Dumpling House", pickupSpotId: "catholic-charities-of-los-angeles-loaves-and-fishe", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest45", name: "Poke Bowl", pickupSpotId: "catholic-charities-of-los-angeles-loaves-and-fishe", description: "Hawaiian-style poke", hours: "10am-3pm" },
  { id: "rest46", name: "Taco Haven", pickupSpotId: "catholic-charities-of-los-angeles-st-margarets-cen", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest47", name: "Pizza Slice", pickupSpotId: "catholic-charities-of-los-angeles-st-roberts-cente", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest48", name: "Curry House", pickupSpotId: "catholic-charities-of-los-angeles-st-roberts-cente", description: "Warm Indian curries", hours: "11am-4pm" },
  { id: "rest49", name: "Sandwich Spot", pickupSpotId: "centro-santo-tomas", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest50", name: "Breakfast Club", pickupSpotId: "charisma-life-church", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest51", name: "Juice Bar", pickupSpotId: "charisma-life-church", description: "Fresh pressed juices", hours: "9am-1pm" },
  { id: "rest52", name: "Burger Barn", pickupSpotId: "chatsworth-charter-high-school", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest53", name: "BBQ Stop", pickupSpotId: "christian-outreach-in-action", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest54", name: "Rice Bowl Co", pickupSpotId: "christian-outreach-in-action", description: "Asian-style rice bowls", hours: "10am-2pm" },
  { id: "rest55", name: "The Deli", pickupSpotId: "church-of-the-redeemer", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest56", name: "Salad Works", pickupSpotId: "city-of-baldwin-park-department-of-recreation-and-", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest57", name: "Waffle House", pickupSpotId: "city-of-baldwin-park-department-of-recreation-and-", description: "Sweet and savory waffles", hours: "8am-1pm" },
  { id: "rest58", name: "Mediterranean Spot", pickupSpotId: "city-of-cudahy-parks-and-recreation-department-cla", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest59", name: "Taqueria Local", pickupSpotId: "city-of-los-angeles-housing-and-community-investme", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest60", name: "Bento Box", pickupSpotId: "city-of-los-angeles-housing-and-community-investme", description: "Japanese bento meals", hours: "12pm-5pm" },
  { id: "rest61", name: "The Grain Bowl", pickupSpotId: "city-of-paramount-department-of-parks-and-recreati", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest62", name: "Empanada Stand", pickupSpotId: "cochran-middle-school", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest63", name: "Noodle Bar", pickupSpotId: "cochran-middle-school", description: "Stir-fried noodle dishes", hours: "12pm-4pm" },
  { id: "rest64", name: "Crepe Cart", pickupSpotId: "columbus-middle-school", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest65", name: "The Bakery", pickupSpotId: "community-outreach-center", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest66", name: "Falafel King", pickupSpotId: "community-outreach-center", description: "Crispy falafel wraps", hours: "10am-4pm" },
  { id: "rest67", name: "Dumpling House", pickupSpotId: "curtiss-middle-school", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest68", name: "Taco Haven", pickupSpotId: "dana-middle-school", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest69", name: "Veggie Bowl", pickupSpotId: "dana-middle-school", description: "Healthy vegan bowls", hours: "10am-2pm" },
  { id: "rest70", name: "Pizza Slice", pickupSpotId: "dorsey-senior-high-school", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest71", name: "Sandwich Spot", pickupSpotId: "dr-julian-nava-learning-academy", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest72", name: "Soup Kitchen", pickupSpotId: "dr-julian-nava-learning-academy", description: "Hot soup and bread", hours: "11am-5pm" },
  { id: "rest73", name: "Breakfast Club", pickupSpotId: "dream-center-the", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest74", name: "Burger Barn", pickupSpotId: "dymally-high-school", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest75", name: "Pasta Place", pickupSpotId: "dymally-high-school", description: "Homemade pasta dishes", hours: "11am-3pm" },
  { id: "rest76", name: "BBQ Stop", pickupSpotId: "eagle-rock-high-school", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest77", name: "The Deli", pickupSpotId: "east-valley-senior-high-school", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest78", name: "Pho Corner", pickupSpotId: "east-valley-senior-high-school", description: "Vietnamese noodle soup", hours: "11am-4pm" },
  { id: "rest79", name: "Salad Works", pickupSpotId: "eastmont-community-center", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest80", name: "Mediterranean Spot", pickupSpotId: "edison-middle-school", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest81", name: "Smoothie Stand", pickupSpotId: "edison-middle-school", description: "Fresh fruit smoothies", hours: "9am-2pm" },
  { id: "rest82", name: "Taqueria Local", pickupSpotId: "ellen-ochoa-learning-center", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest83", name: "The Grain Bowl", pickupSpotId: "epiphany-episcopal-church-lincoln-heights", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest84", name: "Hot Plates", pickupSpotId: "epiphany-episcopal-church-lincoln-heights", description: "Daily hot plate specials", hours: "11am-5pm" },
  { id: "rest85", name: "Empanada Stand", pickupSpotId: "fairfax-senior-high-school", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest86", name: "Crepe Cart", pickupSpotId: "family-rescue-center", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest87", name: "Wings & Things", pickupSpotId: "family-rescue-center", description: "Crispy chicken wings", hours: "12pm-6pm" },
  { id: "rest88", name: "The Bakery", pickupSpotId: "first-baptist-church-of-long-beach", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest89", name: "Dumpling House", pickupSpotId: "first-new-christian-missionary-baptist-church-food", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest90", name: "Poke Bowl", pickupSpotId: "first-new-christian-missionary-baptist-church-food", description: "Hawaiian-style poke", hours: "10am-3pm" },
  { id: "rest91", name: "Taco Haven", pickupSpotId: "first-united-methodist-church-of-compton", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest92", name: "Pizza Slice", pickupSpotId: "fish-of-west-valley", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest93", name: "Curry House", pickupSpotId: "fish-of-west-valley", description: "Warm Indian curries", hours: "11am-4pm" },
  { id: "rest94", name: "Sandwich Spot", pickupSpotId: "foothill-family-shelter", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest95", name: "Breakfast Club", pickupSpotId: "foothill-unity-center-inc-monrovia", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest96", name: "Juice Bar", pickupSpotId: "foothill-unity-center-inc-monrovia", description: "Fresh pressed juices", hours: "9am-1pm" },
  { id: "rest97", name: "Burger Barn", pickupSpotId: "foothill-unity-center-inc-pasadena", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest98", name: "BBQ Stop", pickupSpotId: "fremont-senior-high-school", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest99", name: "Rice Bowl Co", pickupSpotId: "fremont-senior-high-school", description: "Asian-style rice bowls", hours: "10am-2pm" },
  { id: "rest100", name: "The Deli", pickupSpotId: "friends-in-deed", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest101", name: "Salad Works", pickupSpotId: "fulton-college-preparatory-school", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest102", name: "Waffle House", pickupSpotId: "fulton-college-preparatory-school", description: "Sweet and savory waffles", hours: "8am-1pm" },
  { id: "rest103", name: "Mediterranean Spot", pickupSpotId: "gage-middle-school", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest104", name: "Taqueria Local", pickupSpotId: "garfield-senior-high-school", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest105", name: "Bento Box", pickupSpotId: "garfield-senior-high-school", description: "Japanese bento meals", hours: "12pm-5pm" },
  { id: "rest106", name: "The Grain Bowl", pickupSpotId: "gompers-middle-school", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest107", name: "Empanada Stand", pickupSpotId: "grace-resources-inc", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest108", name: "Noodle Bar", pickupSpotId: "grace-resources-inc", description: "Stir-fried noodle dishes", hours: "12pm-4pm" },
  { id: "rest109", name: "Crepe Cart", pickupSpotId: "grateful-hearts", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest110", name: "The Bakery", pickupSpotId: "harte-preparatory-middle-school", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest111", name: "Falafel King", pickupSpotId: "harte-preparatory-middle-school", description: "Crispy falafel wraps", hours: "10am-4pm" },
  { id: "rest112", name: "Dumpling House", pickupSpotId: "hathawaysycamores-family-resource-center-los-angel", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest113", name: "Taco Haven", pickupSpotId: "heart-of-compassion-distribution", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest114", name: "Veggie Bowl", pickupSpotId: "heart-of-compassion-distribution", description: "Healthy vegan bowls", hours: "10am-2pm" },
  { id: "rest115", name: "Pizza Slice", pickupSpotId: "help-me-help-you-philadelphian-sda-church", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest116", name: "Sandwich Spot", pickupSpotId: "help-me-help-you-stevenson-elementary-school", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest117", name: "Soup Kitchen", pickupSpotId: "help-me-help-you-stevenson-elementary-school", description: "Hot soup and bread", hours: "11am-5pm" },
  { id: "rest118", name: "Breakfast Club", pickupSpotId: "hollenbeck-middle-school", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest119", name: "Burger Barn", pickupSpotId: "hollypark-umc-outreach-program", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest120", name: "Pasta Place", pickupSpotId: "hollypark-umc-outreach-program", description: "Homemade pasta dishes", hours: "11am-3pm" },
  { id: "rest121", name: "BBQ Stop", pickupSpotId: "hope-chapel-hermosa-beach", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest122", name: "The Deli", pickupSpotId: "hopenet-blessed-sacrament", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest123", name: "Pho Corner", pickupSpotId: "hopenet-blessed-sacrament", description: "Vietnamese noodle soup", hours: "11am-4pm" },
  { id: "rest124", name: "Salad Works", pickupSpotId: "hopenet-first-baptist-church", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest125", name: "Mediterranean Spot", pickupSpotId: "maywood-center-for-enriched-studies-maces-magnet", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest126", name: "Smoothie Stand", pickupSpotId: "maywood-center-for-enriched-studies-maces-magnet", description: "Fresh fruit smoothies", hours: "9am-2pm" },
  { id: "rest127", name: "Taqueria Local", pickupSpotId: "hopenet-first-church-of-the-nazarene", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest128", name: "The Grain Bowl", pickupSpotId: "hopenet-first-unitarian", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest129", name: "Hot Plates", pickupSpotId: "hopenet-first-unitarian", description: "Daily hot plate specials", hours: "11am-5pm" },
  { id: "rest130", name: "Empanada Stand", pickupSpotId: "hopenet-immanuel-presbyterian-church", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest131", name: "Crepe Cart", pickupSpotId: "hopenet-islamic-center", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest132", name: "Wings & Things", pickupSpotId: "hopenet-islamic-center", description: "Crispy chicken wings", hours: "12pm-6pm" },
  { id: "rest133", name: "The Bakery", pickupSpotId: "hopenet-metropolitan-community-church", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest134", name: "Dumpling House", pickupSpotId: "hopenet-silverlake-community-church", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest135", name: "Poke Bowl", pickupSpotId: "hopenet-silverlake-community-church", description: "Hawaiian-style poke", hours: "10am-3pm" },
  { id: "rest136", name: "Taco Haven", pickupSpotId: "hopenet-st-james-episcopal-church", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest137", name: "Pizza Slice", pickupSpotId: "hopenet-st-johns-episcopal", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest138", name: "Curry House", pickupSpotId: "hopenet-st-johns-episcopal", description: "Warm Indian curries", hours: "11am-4pm" },
  { id: "rest139", name: "Sandwich Spot", pickupSpotId: "hopenet-wilshire-boulevard-temple", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest140", name: "Breakfast Club", pickupSpotId: "hopenet-wilshire-presbyterian-church", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest141", name: "Juice Bar", pickupSpotId: "hopenet-wilshire-presbyterian-church", description: "Fresh pressed juices", hours: "9am-1pm" },
  { id: "rest142", name: "Burger Barn", pickupSpotId: "house-of-yahweh", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest143", name: "BBQ Stop", pickupSpotId: "ilm-foundation", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest144", name: "Rice Bowl Co", pickupSpotId: "ilm-foundation", description: "Asian-style rice bowls", hours: "10am-2pm" },
  { id: "rest145", name: "The Deli", pickupSpotId: "interfaith-food-center", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest146", name: "Salad Works", pickupSpotId: "joy-community-outreach-to-end-homelessness", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest147", name: "Waffle House", pickupSpotId: "joy-community-outreach-to-end-homelessness", description: "Sweet and savory waffles", hours: "8am-1pm" },
  { id: "rest148", name: "Mediterranean Spot", pickupSpotId: "karsh-family-social-service-center", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest149", name: "Taqueria Local", pickupSpotId: "kennedy-austin-foundation", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest150", name: "Bento Box", pickupSpotId: "kennedy-austin-foundation", description: "Japanese bento meals", hours: "12pm-5pm" },
  { id: "rest151", name: "The Grain Bowl", pickupSpotId: "kennedy-high-school", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest152", name: "Empanada Stand", pickupSpotId: "khalsa-care-foundation", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest153", name: "Noodle Bar", pickupSpotId: "khalsa-care-foundation", description: "Stir-fried noodle dishes", hours: "12pm-4pm" },
  { id: "rest154", name: "Crepe Cart", pickupSpotId: "latino-equality-alliance-mi-centro-pride-pantry", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest155", name: "The Bakery", pickupSpotId: "liechty-middle-school", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest156", name: "Falafel King", pickupSpotId: "liechty-middle-school", description: "Crispy falafel wraps", hours: "10am-4pm" },
  { id: "rest157", name: "Dumpling House", pickupSpotId: "lincoln-senior-high-school", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest158", name: "Taco Haven", pickupSpotId: "los-angeles-academy-middle-school", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest159", name: "Veggie Bowl", pickupSpotId: "los-angeles-academy-middle-school", description: "Healthy vegan bowls", hours: "10am-2pm" },
  { id: "rest160", name: "Pizza Slice", pickupSpotId: "los-angeles-county-workforce-development-aging-and", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest161", name: "Sandwich Spot", pickupSpotId: "los-angeles-county-workforce-development-aging-and-2", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest162", name: "Soup Kitchen", pickupSpotId: "los-angeles-county-workforce-development-aging-and-2", description: "Hot soup and bread", hours: "11am-5pm" },
  { id: "rest163", name: "Breakfast Club", pickupSpotId: "los-angeles-county-workforce-development-aging-and-3", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest164", name: "Burger Barn", pickupSpotId: "los-angeles-county-workforce-development-aging-and-4", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest165", name: "Pasta Place", pickupSpotId: "los-angeles-county-workforce-development-aging-and-4", description: "Homemade pasta dishes", hours: "11am-3pm" },
  { id: "rest166", name: "BBQ Stop", pickupSpotId: "los-angeles-county-workforce-development-aging-and-5", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest167", name: "The Deli", pickupSpotId: "los-angeles-county-workforce-development-aging-and-6", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest168", name: "Pho Corner", pickupSpotId: "los-angeles-county-workforce-development-aging-and-6", description: "Vietnamese noodle soup", hours: "11am-4pm" },
  { id: "rest169", name: "Salad Works", pickupSpotId: "los-angeles-county-workforce-development-aging-and-7", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest170", name: "Mediterranean Spot", pickupSpotId: "los-angeles-county-workforce-development-aging-and-8", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest171", name: "Smoothie Stand", pickupSpotId: "los-angeles-county-workforce-development-aging-and-8", description: "Fresh fruit smoothies", hours: "9am-2pm" },
  { id: "rest172", name: "Taqueria Local", pickupSpotId: "los-angeles-regional-food-bank", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest173", name: "The Grain Bowl", pickupSpotId: "maclay-middle-school", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest174", name: "Hot Plates", pickupSpotId: "maclay-middle-school", description: "Daily hot plate specials", hours: "11am-5pm" },
  { id: "rest175", name: "Empanada Stand", pickupSpotId: "manual-arts-high-school", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest176", name: "Crepe Cart", pickupSpotId: "marina-del-rey-middle-school", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest177", name: "Wings & Things", pickupSpotId: "marina-del-rey-middle-school", description: "Crispy chicken wings", hours: "12pm-6pm" },
  { id: "rest178", name: "The Bakery", pickupSpotId: "markham-middle-school", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest179", name: "Dumpling House", pickupSpotId: "marquez-senior-high-school", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest180", name: "Poke Bowl", pickupSpotId: "marquez-senior-high-school", description: "Hawaiian-style poke", hours: "10am-3pm" },
  { id: "rest181", name: "Taco Haven", pickupSpotId: "mother-of-sorrows-catholic-church", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest182", name: "Pizza Slice", pickupSpotId: "msgr-wood-community-center", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest183", name: "Curry House", pickupSpotId: "msgr-wood-community-center", description: "Warm Indian curries", hours: "11am-4pm" },
  { id: "rest184", name: "Sandwich Spot", pickupSpotId: "muir-middle-school", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest185", name: "Breakfast Club", pickupSpotId: "mulholland-middle-school", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest186", name: "Juice Bar", pickupSpotId: "mulholland-middle-school", description: "Fresh pressed juices", hours: "9am-1pm" },
  { id: "rest187", name: "Burger Barn", pickupSpotId: "my-friends-house-inc", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest188", name: "BBQ Stop", pickupSpotId: "narbonne-senior-high-school", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest189", name: "Rice Bowl Co", pickupSpotId: "narbonne-senior-high-school", description: "Asian-style rice bowls", hours: "10am-2pm" },
  { id: "rest190", name: "The Deli", pickupSpotId: "north-hollywood-interfaith-food-pantry", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest191", name: "Salad Works", pickupSpotId: "north-valley-caring-services-inc", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest192", name: "Waffle House", pickupSpotId: "north-valley-caring-services-inc", description: "Sweet and savory waffles", hours: "8am-1pm" },
  { id: "rest193", name: "Mediterranean Spot", pickupSpotId: "our-lady-queen-of-angels-catholic-church", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest194", name: "Taqueria Local", pickupSpotId: "our-saviour-center", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest195", name: "Bento Box", pickupSpotId: "our-saviour-center", description: "Japanese bento meals", hours: "12pm-5pm" },
  { id: "rest196", name: "The Grain Bowl", pickupSpotId: "palmdale-7th-day-adventist-church-community-servic", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest197", name: "Empanada Stand", pickupSpotId: "palms-middle-school", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest198", name: "Noodle Bar", pickupSpotId: "palms-middle-school", description: "Stir-fried noodle dishes", hours: "12pm-4pm" },
  { id: "rest199", name: "Crepe Cart", pickupSpotId: "panorama-senior-high-school", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest200", name: "The Bakery", pickupSpotId: "peace-lutheran-church", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest201", name: "Falafel King", pickupSpotId: "peace-lutheran-church", description: "Crispy falafel wraps", hours: "10am-4pm" },
  { id: "rest202", name: "Dumpling House", pickupSpotId: "peary-middle-school", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest203", name: "Taco Haven", pickupSpotId: "pico-union-project", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest204", name: "Veggie Bowl", pickupSpotId: "pico-union-project", description: "Healthy vegan bowls", hours: "10am-2pm" },
  { id: "rest205", name: "Pizza Slice", pickupSpotId: "porter-middle-school", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest206", name: "Sandwich Spot", pickupSpotId: "rancho-dominguez-preparatory-school", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest207", name: "Soup Kitchen", pickupSpotId: "rancho-dominguez-preparatory-school", description: "Hot soup and bread", hours: "11am-5pm" },
  { id: "rest208", name: "Breakfast Club", pickupSpotId: "rescue-mission-alliance-valley-food-bank-calvary-b", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest209", name: "Burger Barn", pickupSpotId: "rescue-mission-alliance-valley-food-bank-leaves-of", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest210", name: "Pasta Place", pickupSpotId: "rescue-mission-alliance-valley-food-bank-leaves-of", description: "Homemade pasta dishes", hours: "11am-3pm" },
  { id: "rest211", name: "BBQ Stop", pickupSpotId: "rescue-mission-alliance-valley-food-bank-new-hope-", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest212", name: "The Deli", pickupSpotId: "rescue-mission-alliance-valley-food-bank-rock-of-t", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest213", name: "Pho Corner", pickupSpotId: "rescue-mission-alliance-valley-food-bank-rock-of-t", description: "Vietnamese noodle soup", hours: "11am-4pm" },
  { id: "rest214", name: "Salad Works", pickupSpotId: "rescue-mission-alliance-valley-food-bank-st-andrew", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest215", name: "Mediterranean Spot", pickupSpotId: "rescue-mission-alliance-valley-food-bank-the-house", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest216", name: "Smoothie Stand", pickupSpotId: "rescue-mission-alliance-valley-food-bank-the-house", description: "Fresh fruit smoothies", hours: "9am-2pm" },
  { id: "rest217", name: "Taqueria Local", pickupSpotId: "rescue-mission-alliance-valley-food-bank-valley-ko", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest218", name: "The Grain Bowl", pickupSpotId: "rescue-mission-alliance-valley-food-bank-valley-pa", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest219", name: "Hot Plates", pickupSpotId: "rescue-mission-alliance-valley-food-bank-valley-pa", description: "Daily hot plate specials", hours: "11am-5pm" },
  { id: "rest220", name: "Empanada Stand", pickupSpotId: "rfkucla-community-school", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest221", name: "Crepe Cart", pickupSpotId: "romer-middle-school", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest222", name: "Wings & Things", pickupSpotId: "romer-middle-school", description: "Crispy chicken wings", hours: "12pm-6pm" },
  { id: "rest223", name: "The Bakery", pickupSpotId: "saint-mark-united-methodist-church", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest224", name: "Dumpling House", pickupSpotId: "salvation-army-southern-california-divisional-head", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest225", name: "Poke Bowl", pickupSpotId: "salvation-army-southern-california-divisional-head", description: "Hawaiian-style poke", hours: "10am-3pm" },
  { id: "rest226", name: "Taco Haven", pickupSpotId: "salvation-army-stillman-sawyer-family-center", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest227", name: "Pizza Slice", pickupSpotId: "salvation-army-corps-community-center-compton", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest228", name: "Curry House", pickupSpotId: "salvation-army-corps-community-center-compton", description: "Warm Indian curries", hours: "11am-4pm" },
  { id: "rest229", name: "Sandwich Spot", pickupSpotId: "salvation-army-corps-community-center-east-los-ang", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest230", name: "Breakfast Club", pickupSpotId: "salvation-army-corps-community-center-glendale", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest231", name: "Juice Bar", pickupSpotId: "salvation-army-corps-community-center-glendale", description: "Fresh pressed juices", hours: "9am-1pm" },
  { id: "rest232", name: "Burger Barn", pickupSpotId: "salvation-army-corps-community-center-long-beach", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest233", name: "BBQ Stop", pickupSpotId: "salvation-army-corps-community-center-santa-monica", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest234", name: "Rice Bowl Co", pickupSpotId: "salvation-army-corps-community-center-santa-monica", description: "Asian-style rice bowls", hours: "10am-2pm" },
  { id: "rest235", name: "The Deli", pickupSpotId: "salvation-army-corps-community-center-south-centra", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest236", name: "Salad Works", pickupSpotId: "salvation-army-corps-family-service-center-san-ped", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest237", name: "Waffle House", pickupSpotId: "salvation-army-corps-family-service-center-san-ped", description: "Sweet and savory waffles", hours: "8am-1pm" },
  { id: "rest238", name: "Mediterranean Spot", pickupSpotId: "salvation-army-service-extension-office-newhall", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest239", name: "Taqueria Local", pickupSpotId: "salvation-army-southeast-communities-corp-huntingt", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest240", name: "Bento Box", pickupSpotId: "salvation-army-southeast-communities-corp-huntingt", description: "Japanese bento meals", hours: "12pm-5pm" },
  { id: "rest241", name: "The Grain Bowl", pickupSpotId: "san-fernando-senior-high-school", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest242", name: "Empanada Stand", pickupSpotId: "san-gabriel-mission-christian-service-center", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest243", name: "Noodle Bar", pickupSpotId: "san-gabriel-mission-christian-service-center", description: "Stir-fried noodle dishes", hours: "12pm-4pm" },
  { id: "rest244", name: "Crepe Cart", pickupSpotId: "santa-clarita-valley-food-pantry", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest245", name: "The Bakery", pickupSpotId: "santee-high-school", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest246", name: "Falafel King", pickupSpotId: "santee-high-school", description: "Crispy falafel wraps", hours: "10am-4pm" },
  { id: "rest247", name: "Dumpling House", pickupSpotId: "sepulveda-middle-school", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest248", name: "Taco Haven", pickupSpotId: "shekinah-worship-center", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest249", name: "Veggie Bowl", pickupSpotId: "shekinah-worship-center", description: "Healthy vegan bowls", hours: "10am-2pm" },
  { id: "rest250", name: "Pizza Slice", pickupSpotId: "shepherds-pantry", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest251", name: "Sandwich Spot", pickupSpotId: "shepherds-pantry-baldwin-park", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest252", name: "Soup Kitchen", pickupSpotId: "shepherds-pantry-baldwin-park", description: "Hot soup and bread", hours: "11am-5pm" },
  { id: "rest253", name: "Breakfast Club", pickupSpotId: "shepherds-pantry-glendora", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest254", name: "Burger Barn", pickupSpotId: "sotomayor-artssciences-magnet", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest255", name: "Pasta Place", pickupSpotId: "sotomayor-artssciences-magnet", description: "Homemade pasta dishes", hours: "11am-3pm" },
  { id: "rest256", name: "BBQ Stop", pickupSpotId: "south-east-senior-high-school", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest257", name: "The Deli", pickupSpotId: "south-gate-senior-high-school", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest258", name: "Pho Corner", pickupSpotId: "south-gate-senior-high-school", description: "Vietnamese noodle soup", hours: "11am-4pm" },
  { id: "rest259", name: "Salad Works", pickupSpotId: "sova-food-pantry-and-resource-center-valley", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest260", name: "Mediterranean Spot", pickupSpotId: "sova-food-pantry-and-resource-center-west", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest261", name: "Smoothie Stand", pickupSpotId: "sova-food-pantry-and-resource-center-west", description: "Fresh fruit smoothies", hours: "9am-2pm" },
  { id: "rest262", name: "Taqueria Local", pickupSpotId: "sowing-seeds-for-life", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest263", name: "The Grain Bowl", pickupSpotId: "st-athanasius-and-st-paul", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest264", name: "Hot Plates", pickupSpotId: "st-athanasius-and-st-paul", description: "Daily hot plate specials", hours: "11am-5pm" },
  { id: "rest265", name: "Empanada Stand", pickupSpotId: "st-augustine-volunteer-emergency-services", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest266", name: "Crepe Cart", pickupSpotId: "st-charles-holy-family-service-center", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest267", name: "Wings & Things", pickupSpotId: "st-charles-holy-family-service-center", description: "Crispy chicken wings", hours: "12pm-6pm" },
  { id: "rest268", name: "The Bakery", pickupSpotId: "st-elisabeth-catholic-church-service-center-distri", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest269", name: "Dumpling House", pickupSpotId: "st-ferdinand-outreach-center", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest270", name: "Poke Bowl", pickupSpotId: "st-ferdinand-outreach-center", description: "Hawaiian-style poke", hours: "10am-3pm" },
  { id: "rest271", name: "Taco Haven", pickupSpotId: "st-frances-of-rome-food-bank", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest272", name: "Pizza Slice", pickupSpotId: "st-gerard-majella-church", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest273", name: "Curry House", pickupSpotId: "st-gerard-majella-church", description: "Warm Indian curries", hours: "11am-4pm" },
  { id: "rest274", name: "Sandwich Spot", pickupSpotId: "st-gregorys-episcopal-church", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest275", name: "Breakfast Club", pickupSpotId: "st-johns-episcopal-cathedral", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest276", name: "Juice Bar", pickupSpotId: "st-johns-episcopal-cathedral", description: "Fresh pressed juices", hours: "9am-1pm" },
  { id: "rest277", name: "Burger Barn", pickupSpotId: "st-joseph-center", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest278", name: "BBQ Stop", pickupSpotId: "st-lawrence-martyr-catholic-church", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest279", name: "Rice Bowl Co", pickupSpotId: "st-lawrence-martyr-catholic-church", description: "Asian-style rice bowls", hours: "10am-2pm" },
  { id: "rest280", name: "The Deli", pickupSpotId: "st-lawrence-of-brindisi", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest281", name: "Salad Works", pickupSpotId: "st-margaret-marys-christian-services", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest282", name: "Waffle House", pickupSpotId: "st-margaret-marys-christian-services", description: "Sweet and savory waffles", hours: "8am-1pm" },
  { id: "rest283", name: "Mediterranean Spot", pickupSpotId: "st-martin-de-porres-outreach-center", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest284", name: "Taqueria Local", pickupSpotId: "st-philips-episcopal-church", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest285", name: "Bento Box", pickupSpotId: "st-philips-episcopal-church", description: "Japanese bento meals", hours: "12pm-5pm" },
  { id: "rest286", name: "The Grain Bowl", pickupSpotId: "st-philomena-church", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest287", name: "Empanada Stand", pickupSpotId: "st-timothy-church", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest288", name: "Noodle Bar", pickupSpotId: "st-timothy-church", description: "Stir-fried noodle dishes", hours: "12pm-4pm" },
  { id: "rest289", name: "Crepe Cart", pickupSpotId: "st-francis-center", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest290", name: "The Bakery", pickupSpotId: "sutter-middle-school", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest291", name: "Falafel King", pickupSpotId: "sutter-middle-school", description: "Crispy falafel wraps", hours: "10am-4pm" },
  { id: "rest292", name: "Dumpling House", pickupSpotId: "sylmar-charter-high-school", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest293", name: "Taco Haven", pickupSpotId: "tamarind-avenue-7th-day-adventist-church", description: "Fresh Mexican food daily", hours: "11am-3pm" },
  { id: "rest294", name: "Veggie Bowl", pickupSpotId: "tamarind-avenue-7th-day-adventist-church", description: "Healthy vegan bowls", hours: "10am-2pm" },
  { id: "rest295", name: "Pizza Slice", pickupSpotId: "toberman-neighborhood-center", description: "Hot pizza slices", hours: "12pm-4pm" },
  { id: "rest296", name: "Sandwich Spot", pickupSpotId: "trinity-baptist-church", description: "Daily sandwich specials", hours: "12pm-4pm" },
  { id: "rest297", name: "Soup Kitchen", pickupSpotId: "trinity-baptist-church", description: "Hot soup and bread", hours: "11am-5pm" },
  { id: "rest298", name: "Breakfast Club", pickupSpotId: "university-high-school-charter", description: "Morning eggs and toast", hours: "8am-12pm" },
  { id: "rest299", name: "Burger Barn", pickupSpotId: "valley-beth-shalom", description: "Fresh burgers and fries", hours: "1pm-6pm" },
  { id: "rest300", name: "Pasta Place", pickupSpotId: "valley-beth-shalom", description: "Homemade pasta dishes", hours: "11am-3pm" },
  { id: "rest301", name: "BBQ Stop", pickupSpotId: "van-nuys-senior-high-school", description: "Slow smoked meats", hours: "12pm-5pm" },
  { id: "rest302", name: "The Deli", pickupSpotId: "verdugo-hills-senior-high-school", description: "Classic deli sandwiches", hours: "10am-3pm" },
  { id: "rest303", name: "Pho Corner", pickupSpotId: "verdugo-hills-senior-high-school", description: "Vietnamese noodle soup", hours: "11am-4pm" },
  { id: "rest304", name: "Salad Works", pickupSpotId: "virgil-middle-school", description: "Fresh garden salads", hours: "11am-3pm" },
  { id: "rest305", name: "Mediterranean Spot", pickupSpotId: "washington-preparatory-senior-high-school", description: "Falafel and hummus wraps", hours: "11am-4pm" },
  { id: "rest306", name: "Smoothie Stand", pickupSpotId: "washington-preparatory-senior-high-school", description: "Fresh fruit smoothies", hours: "9am-2pm" },
  { id: "rest307", name: "Taqueria Local", pickupSpotId: "wayside-united-methodist-church", description: "Street-style tacos", hours: "10am-3pm" },
  { id: "rest308", name: "The Grain Bowl", pickupSpotId: "west-angeles-community-development-corporation-com", description: "Wholesome grain bowls", hours: "10am-3pm" },
  { id: "rest309", name: "Hot Plates", pickupSpotId: "west-angeles-community-development-corporation-com", description: "Daily hot plate specials", hours: "11am-5pm" },
  { id: "rest310", name: "Empanada Stand", pickupSpotId: "west-valley-food-pantry", description: "Freshly baked empanadas", hours: "9am-2pm" },
  { id: "rest311", name: "Crepe Cart", pickupSpotId: "west-washington-l-a-foursquare-church", description: "Sweet and savory crepes", hours: "9am-1pm" },
  { id: "rest312", name: "Wings & Things", pickupSpotId: "west-washington-l-a-foursquare-church", description: "Crispy chicken wings", hours: "12pm-6pm" },
  { id: "rest313", name: "The Bakery", pickupSpotId: "white-middle-school", description: "Fresh breads and pastries", hours: "7am-12pm" },
  { id: "rest314", name: "Dumpling House", pickupSpotId: "wilson-senior-high-school", description: "Steamed and fried dumplings", hours: "11am-5pm" },
  { id: "rest315", name: "Poke Bowl", pickupSpotId: "wilson-senior-high-school", description: "Hawaiian-style poke", hours: "10am-3pm" },
  { id: "rest316", name: "Taco Haven", pickupSpotId: "world-harvest-food-bank", description: "Fresh Mexican food daily", hours: "11am-3pm" },
];

export const mockFoods = [
  // Taco Haven (rest1)
  { id: "food1", restaurantId: "rest1", name: "Chicken Tacos", type: "Hot meal", notes: "Gluten-free option", availableUntil: "15:00" },
  { id: "food2", restaurantId: "rest1", name: "Veggie Burritos", type: "Hot meal", notes: "Vegetarian", availableUntil: "14:30" },
  
  // Veggie Bowl (rest2)
  { id: "food3", restaurantId: "rest2", name: "Quinoa Bowl", type: "Healthy meal", notes: "Vegan", availableUntil: "14:00" },
  
  // Sandwich Spot (rest4)
  { id: "food4", restaurantId: "rest4", name: "Turkey Sandwiches", type: "Sandwich", notes: "Kid-friendly", availableUntil: "16:00" },
  { id: "food5", restaurantId: "rest4", name: "Fruit Cups", type: "Snack", notes: "Fresh fruit", availableUntil: "15:30" },
  
  // Soup Kitchen (rest5)
  { id: "food6", restaurantId: "rest5", name: "Chicken Noodle Soup", type: "Soup", notes: "Warm & hearty", availableUntil: "17:00" }
];